-- Seed data hasil migrasi dari bots.json & news.js (dijalankan sekali setelah schema.sql)

INSERT INTO bots (name, description, owner, language, home, help, library_name, library_public, active, uptime, tags, usage_prefix) VALUES
  ('acechar', NULL, 'manuel', 'python', 'dinastiadark', '*cmds', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"entertainment","moderation","utility"}', '{"*"}'),
  ('acleebot', NULL, 'aclee', 'python', 'acoleekek', '!cmds', 'ch.py', 'https://github.com/acleee/acleebot/blob/master/chatango/ch.py', FALSE, 0, '{"entertainment","utility"}', '{"!"}'),
  ('afpy', NULL, 'vf', 'python', 'x7z', NULL, 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"english","entertainment","information","utility"}', '{"#"}'),
  ('aparecera', NULL, 'agung', 'ruby', NULL, ',wl ,cmds', 'chatango-ruby', 'https://github.com/agunq/chatango-ruby', TRUE, 88, '{"english","information","utility"}', '{","}'),
  ('automod', 'A moderation bot for Chatango groups.', 'cheese', 'javascript', 'community', NULL, 'apple.js', NULL, FALSE, 0, '{"english","entertainment","customizable"}', '{"/"}'),
  ('azusafreya', NULL, 'rehanyusuf', 'python', 'smatag', '.cmds', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"english","indonesian","entertainment","information","moderation","utility"}', '{"."}'),
  ('b0t', NULL, 'barry', 'javascript', 'b0tty', '/cl', 'derplib.js', 'https://github.com/MakuraYami/derplib', FALSE, 96, '{"english","entertainment","information","roleplay","economy","utility","anime"}', '{"/","."}'),
  ('baymax', NULL, 'ultimo', 'javascript', 'sanfransokyo', '$wl', 'mechon.js', 'https://github.com/talenfisher/mechon', FALSE, 0, '{"english","entertainment","information","economy","utility"}', '{"$"}'),
  ('blackrockshooter', NULL, 'theclonerx', 'python', 'clonerx', NULL, 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"english","entertainment","utility"}', '{"!"}'),
  ('botteh', NULL, 'sorch', 'javascript', 'projectbotteh', ':help', NULL, NULL, FALSE, 0, '{"english","entertainment","information","roleplay","utility"}', '{":"}'),
  ('bros', NULL, 'pichu', 'javascript', 'projectbros', '-cmds', 'coco.js', NULL, TRUE, 98, '{"english","entertainment","customizable","information","moderation","utility"}', '{"-"}'),
  ('butthole', NULL, 'herenti', 'python', 'garden', '*cmds', 'cakelib2.py', 'https://github.com/herenti/chatango', FALSE, 50, '{"english","entertainment"}', '{"*"}'),
  ('cctvbot', NULL, 'planero', 'python', 'chatterslodge', '-cmd', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"entertainment","moderation","utility"}', '{"-"}'),
  ('devilsona', 'sona worst support but still my waifu', 'agung', 'ruby', 'nico-nico', ',wl ,cmds', 'chatango-ruby', 'https://github.com/agunq/chatango-ruby', FALSE, 88, '{"english","information","utility"}', '{","}'),
  ('droid', 'A multipurpose bot for Chatango groups and Discord servers.', 'cheese', 'python', 'network', '/commands', 'android.py', NULL, FALSE, 80, '{"english","entertainment","customizable","moderation","information","roleplay","economy","logging","utility","anime"}', '{"/"}'),
  ('eg', NULL, 'notconnect', 'python', 'nico-nico', '=cmds', 'ch.py', 'https://github.com/nhammond129/ch.py', TRUE, 85, '{"english","utility","information","moderation","entertainment"}', '{"="}'),
  ('h04x', '&lt;screw js&gt;', 'agung', 'javascript', NULL, NULL, 'ch.js', NULL, FALSE, 88, '{"english","information","utility"}', '{","}'),
  ('hackeybot', NULL, 'brahseal', 'python', 'testingbotfam', '@hackeybot', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"entertainment","utility"}', '{"!","$","#","."}'),
  ('hanabei', NULL, 'soda', 'python', 'animeultimacom', '.wl', NULL, NULL, FALSE, 0, '{"english","entertainment","roleplay","economy","utility","anime"}', '{"."}'),
  ('haqua', NULL, 'shiroehellscythe', 'python', 'thegraygarden', NULL, 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"english","entertainment","utility"}', '{"-"}'),
  ('hatterbot', NULL, 'patricksoyanuchiha', 'python', 'animekaibr', '!cmds', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 85, '{"english","utility","information","moderation","entertainment"}', '{"!"}'),
  ('hinkiebot', NULL, 'eagles95', 'python', 'hinkiebottesterxd', NULL, 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 88, '{"english","information"}', '{"/"}'),
  ('intellect', NULL, 'coil', 'python', 'rmrf', '/help', 'cherryblossom.py', 'https://github.com/Sweets/Cherry-Blossom', FALSE, 0, '{"english","entertainment","moderation","roleplay","economy","utility"}', '{"/"}'),
  ('kairy', NULL, 'tite05', 'python', 'kairyhome', NULL, 'megach.py', 'https://github.com/Milton797/chatango-bot', FALSE, 40, '{"english","entertainment","utility"}', '{"+"}'),
  ('koredroid', NULL, 'opfansloverzz', 'python', 'korenime-official', '/cmds', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 40, '{}', '{"/"}'),
  ('lerxst', NULL, 'donboricua', 'python', 'lerxstbox', ';wl', 'chlib.py', 'https://github.com/Raitisu/chlib', FALSE, 0, '{"english","entertainment","information","utility"}', '{";"}'),
  ('lethebot', NULL, 'lethe', 'c#', NULL, NULL, 'lethebot.cs', NULL, FALSE, 0, '{}', '{"/"}'),
  ('lilycoris', NULL, 'vf', 'python', 'x7z', NULL, 'megach.py', 'https://github.com/Milton797/chatango-bot', FALSE, 0, '{"english","entertainment","information","utility"}', '{"#"}'),
  ('lmaolover', NULL, 'rangerfrex', 'python', 'lmaolove', '/yes', 'ch.py', 'https://github.com/LmaoLover/LmaoBot/blob/master/ch.py', FALSE, 0, '{"english","entertainment","utility"}', '{"/","?","??"}'),
  ('lulubot', NULL, 'fath', 'python', 'feed-lulu', '`cmds', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"information","utility","anime"}', '{"`"}'),
  ('maid', NULL, 'jared', 'python', 'eden', ';register', 'android.py', NULL, FALSE, 0, '{"english","entertainment","information","moderation","roleplay","utility","anime"}', '{";"}'),
  ('mechabot', NULL, 'natsume', 'python', 'kazuplayground', '.wl', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"english","entertainment","roleplay","economy","logging","utility"}', '{"."}'),
  ('myubot', NULL, 'mynua', 'python', 'myub0t', '.cmds', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 85, '{"english","utility","information","moderation","entertainment"}', '{"."}'),
  ('negro', NULL, 'bong', 'python', 'bongstream', NULL, 'ch.py', 'https://github.com/nhammond129/ch.py', TRUE, 90, '{"english","entertainment"}', '{"!"}'),
  ('nekonyan', NULL, 'perorist', 'python', NULL, '.cmds', 'chatango.py', NULL, TRUE, 98, '{"english","entertainment","moderation","logging","utility","anime","chat"}', '{"."}'),
  ('node', NULL, 'hazerd', 'javascript', 'nodeproject', ',help', NULL, NULL, FALSE, 0, '{"english","entertainment","information","utility"}', '{","}'),
  ('nybbit', NULL, 'evan', 'python', 'summit', '/help', NULL, NULL, FALSE, 0, '{"english","entertainment","information","economy","utility"}', '{"/",".",";"}'),
  ('nyu', NULL, 'soda', 'python', 'animeultimacom', '.wl', NULL, NULL, FALSE, 0, '{"english","entertainment","roleplay","economy","utility","anime"}', '{"."}'),
  ('oppaixraider', 'gokunime-com.chatango.com | nico-nico.chatango.com | javersindo.chatango.com |', 'notconnect', 'python', 'nico-nico', '=cmds', 'cerach.py', NULL, FALSE, 65, '{}', '{"="}'),
  ('pegasus507', NULL, 'sahil507', 'python', 'pakmaza', 'pega', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"english","entertainment"}', '{"pega"}'),
  ('pou', NULL, 'anonimo9193', 'python', 'pouplay', ',cl', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"english","entertainment","economy","utility"}', '{","}'),
  ('puppybot', NULL, 'bikesama', 'python', 'main-chatroom', '.cmds', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 85, '{"english","utility","information","moderation","entertainment"}', '{"."}'),
  ('rat', NULL, 'elian', 'python', 'green-land', '-wl', 'ch.py', 'https://github.com/nhammond129/ch.py', TRUE, 20, '{"english","entertainment","information","moderation","roleplay","logging","utility"}', '{"-"}'),
  ('redqueen', NULL, 'kyouma', 'javascript', 'projectumbrella', '`wl', NULL, NULL, FALSE, 0, '{"english","entertainment","information","roleplay","utility"}', '{"`"}'),
  ('reitia', NULL, 'akasakiryuu', 'python', NULL, NULL, 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"english","entertainment","utility"}', '{"+"}'),
  ('rorymercury797', NULL, 'milton797', 'python', NULL, '=cmds', 'megach.py', 'https://github.com/Milton797/chatango-bot', FALSE, 0, '{"english","spanish","entertainment","information","roleplay","utility"}', '{"="}'),
  ('roxvent', NULL, 'megamaster12', 'python', 'pythonrpg', '/wl', 'megach.py', 'https://github.com/Milton797/chatango-bot', FALSE, 60, '{"spanish","entertainment","customizable","moderation","roleplay","utility","anime","chat"}', '{"/"}'),
  ('rubycookies', NULL, 'neokuze', 'python', 'sudoers', '.cmds', 'chatango.py', 'https://github.com/neokuze/chatango-lib', FALSE, 95, '{"entertainment","moderation","utility"}', '{"."}'),
  ('slimeware', NULL, 'talonns', 'python', 'slimewire', '.cmds', NULL, NULL, FALSE, 0, '{"english","entertainment","information","economy","utility"}', '{"."}'),
  ('software', NULL, 'hardware', 'python', 'ch', '!cmds', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"english","entertainment","information","moderation","roleplay","economy","logging","utility","chat"}', '{"!"}'),
  ('terminal', NULL, 'darcey', 'python', 'terminaldebug', '-wl', NULL, NULL, FALSE, 0, '{"english","entertainment","information","moderation","roleplay","utility"}', '{"-"}'),
  ('testkit', NULL, 'ainzsyn', 'javascript', 'omega', '!help', 'derplib.js', 'https://github.com/MakuraYami/derplib', FALSE, 0, '{"english","entertainment","moderation","economy","utility"}', '{"!","-"}'),
  ('thebotx', NULL, 'theclonerx', 'python', 'clonerx', NULL, 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"english","entertainment","utility"}', '{"!"}'),
  ('uqib', NULL, 'yadokun', 'python', 'palaciodehielo', '!cmds', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"entertainment","moderation","utility"}', '{"!"}'),
  ('uri', NULL, 'soda', 'python', 'playwithuri', '.wl', NULL, NULL, FALSE, 0, '{"english","entertainment","roleplay","economy","utility","anime"}', '{"."}'),
  ('vianbot', NULL, 'naunkun', 'python', 'holiprogres', '/cmds', 'ch.py', 'https://github.com/nhammond129/ch.py', TRUE, 95, '{"entertainment","moderation","utility"}', '{"/"}'),
  ('wombot', NULL, 'bbbaaaaa', 'python', 'chuntoo', '!tags', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 0, '{"english","entertainment","utility"}', '{"!"}'),
  ('yadrier', NULL, 'neokuze', 'python', 'robotsplayground', 'help;', 'chatango.py', 'https://github.com/neokuze/chatango-lib', FALSE, 70, '{"english","indonesian","spanish","moderation","utility"}', '{"(command);"}'),
  ('yamada', NULL, 'nosoba', 'python', 'queenslounge', '/cmds', 'ch.py', 'https://github.com/nhammond129/ch.py', FALSE, 70, '{"english","entertainment","utility","anime"}', '{"/","+"}')
ON CONFLICT (name) DO NOTHING;

INSERT INTO news (date, tag, title, body, link) VALUES
  ('2026.09.29', 'INFO', 'Situs resmi dibuka!', 'Selamat datang di situs resmi. Nantikan informasi terbaru di halaman ini.', NULL),
  ('2026.09.20', 'EVENT', 'Contoh judul berita kedua', 'Tulis isi beritamu di sini. Baris baru bisa pakai \n.', 'https://example.com')
ON CONFLICT DO NOTHING;
